language: cpp
os: linux
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:tobydox/mingw-x-precise
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-4.8-multilib g++-4.9-multilib
- sudo apt-get install -qq mingw64-x-gcc mingw32-x-gcc wine
script:
- export PLATFORM=linux
- export LDLIBS=-lrt
- g++-4.8 --version
- ARCH=64 BUILD=debug make CXX=g++-4.8 all test && bin/Test_EasyTest++_linux64_debug
- ARCH=32 BUILD=debug make CXX=g++-4.8 all test && bin/Test_EasyTest++_linux32_debug
- ARCH=64 BUILD=release make CXX=g++-4.8 all test && bin/Test_EasyTest++_linux64_release
- ARCH=32 BUILD=release make CXX=g++-4.8 all test && bin/Test_EasyTest++_linux32_release
- make clean-all
- g++-4.9 --version
- ARCH=64 BUILD=debug make CXX=g++-4.9 all test && bin/Test_EasyTest++_linux64_debug
- ARCH=32 BUILD=debug make CXX=g++-4.9 all test && bin/Test_EasyTest++_linux32_debug
- ARCH=64 BUILD=release make CXX=g++-4.9 all test && bin/Test_EasyTest++_linux64_release
- ARCH=32 BUILD=release make CXX=g++-4.9 all test && bin/Test_EasyTest++_linux32_release
- PLATFORM=mingw
- export -n LDLIBS
- MINGW64=/opt/mingw64/bin/x86_64-w64-mingw32
- $MINGW64-g++ --version
- ARCH=64 BUILD=debug make CXX=$MINGW64-g++ AR=$MINGW64-ar all test && bin/Test_EasyTest++_mingw64_debug.exe
- ARCH=64 BUILD=release make CXX=$MINGW64-g++ AR=$MINGW64-ar all test && bin/Test_EasyTest++_mingw64_release.exe
- MINGW32=/opt/mingw32/bin/i686-w64-mingw32
- $MINGW32-g++ --version
- ARCH=32 BUILD=debug make CXX=$MINGW32-g++ AR=$MINGW32-ar all test && bin/Test_EasyTest++_mingw32_debug.exe
- ARCH=32 BUILD=release make CXX=$MINGW32-g++ AR=$MINGW32-ar all test && bin/Test_EasyTest++_mingw32_release.exe
notifications:
  email:
    on_success: always
